Install mysql gem if not already installed, as it requires sudo

diff --git a/install_redmine b/install_redmine
--- a/install_redmine
+++ b/install_redmine
@@ -142,6 +142,11 @@ if ! $SUDO gem install bundler $PROXY; then
 	echo 'ERROR: Failed to install "bundler". [install bundler]'
 	exit 1
 fi
+# Install mysql gem if not already installed, as it requires sudo
+if ! $SUDO gem install mysql $PROXY; then
+	echo 'ERROR: Failed to install "bundler". [install mysql]'
+	exit 1
+fi
 if ! bundle install --no-deployment --without development test; then
 	echo 'ERROR: Failed to download dependencies. [bundle install].'
 	exit 1
